// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.34.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NLU>>
@sealed
class Nlu extends RustOpaque {
  Nlu.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  Nlu.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Nlu,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Nlu,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NluPtr,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Nlu> newInstance({required String engineDir, dynamic hint}) =>
      RustLib.instance.api
          .crateApiSimpleNluNew(engineDir: engineDir, hint: hint);

  Future<String> parseIntent({required String input, dynamic hint}) =>
      RustLib.instance.api
          .crateApiSimpleNluParseIntent(that: this, input: input, hint: hint);
}
